rvm:
  - 2.2.3
before_script:
  - psql -c 'create database workshops_test;' -U postgres
  - cp config/database.yml.sample config/database.yml
  - bundle exec rake db:create db:schema:load
  - bundle exec rspec
addons:
  postgresql: '9.3'
