rvm:
  - 2.2.3
before_script:
  - cp config/database.yml.sample config/database.yml
  - psql -c 'create database workshops;' -U postgres
  - bundle exec rake db:create db:schema:load
  - bundle exec rspec
cache: bundler
addons:
  postgresql: '9.3'
