rvm:
  - 2.2.3
before_script:
  - cp config/database.yml.sample config/database.yml
  - psql -c "CREATE USER workshops WITH PASSWORD 'workshops';" -U postgres
  - psql -c 'create database workshops_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:schema:load
  - RAILS_ENV=test bundle exec rspec
cache: bundler
addons:
  postgresql: '9.3'
